version: '3'

services:

  # mongodb: 
  #   image: mongo 
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mongo
  #     MONGO_INITDB_ROOT_PASSWORD: cosmos
  #   ports :
  #     - "27017:27017"

  server: 
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment : 
      PORT: 4000
    ports : 
    - "4000:4000"
    networks :
    - default
    # depends_on:
    #   - mongodb

  client: 
    build: 
      context: ./client
      dockerfile: Dockerfile
    environment :
    - REACT_APP_BACKEND=http://host.docker.internal:4000
    ports:
    - 3000:3000
    depends_on:
      - server
    networks :
      - default

